name = "SeisMonitoring_Paper"
uuid = "1f070db4-aea5-4110-82e1-b83941dcfa8c"
authors = ["Kurama Okubo"]
version = "0.1.0"

[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"

[compat]
Documenter = "0.27"
